version: '3.8'

secrets:
  ssh_key:
    file: ~/.ssh/id_rsa

services:

  ####### PHP ######
  dev-server:
    build:
      context: .
      dockerfile: .docker/dev.docker/php7.dev.dockerfile
    environment:
      - TZ=America/Chicago
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
      - ./:/project
      - ./xdebug.info:/xdebug.info
      - ./.docker/php/php.development.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf.d/xdebug.php7.ini:/usr/local/etc/php/conf.d/xdebug.ini
    # The export in the next line overrides the defaults for XDebug set in the xdebug.ini for HTTP.
    command: bash -c 'export XDEBUG_MODE=debug,develop,gcstats,profile,trace XDEBUG_CONFIG="remote_enable=on"; php -S 0.0.0.0:8001 -t /app/html'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - source: ssh_key
        target: /home/user/.ssh/id_rsa

  prod-server:
    build:
      context: .
      dockerfile: .docker/prod.docker/php8.prod.dockerfile
    environment:
      - TZ=America/Chicago
    ports:
      - "8002:80"
    volumes:
      - ./app/html:/var/www/html
      - ./app:/var/www
      - ./.docker/php/php.production.ini:/usr/local/etc/php/php.ini
      # TODO: Map the prod config to a composer development-disable config.  

  ####### Maria DB ########
  db:
    image: mariadb
    environment:
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=i57z9*UIuJQ!
      - collation-server=utf8mb4_unicode_ci
      - character-set-server=utf8mb4
      - MYSQL_DATABASE=database_name
    ports:
      - "5000:3306"
    volumes:
      - ./db-startup:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=America/Chicago
      - PMA_USER=root
      - PMA_PASSWORD=i57z9*UIuJQ!
    ports:
      - "9082:80"

  ####### Redis #######
  redis:
    image: redis
  phpredisadmin:
    image:  erikdubbelboer/phpredisadmin
    environment:
      - TZ=America/Chicago
      - REDIS_1_HOST=redis
    ports:
      - "9083:80"

  ######## Apache AB #######
  performance-testing:
    image: httpd
    environment:
      - TZ=America/Chicago
    volumes:
      - ./performance-testing/:/usr/local/apache2/performance-testing
    ports:
      - "9084:80"
